import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import {
  Box,
  Button,
  Container,
  Divider,
  Flex,
  Spacer,
  Stack,
  Text,
} from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container mb="20" maxW={'6xl'}>
        <Flex
          display={['none', 'none', 'flex']}
          alignItems={'center'}
          justify={['center', 'center', 'space-between']}
          pt={8}
        >
          <Image width={120} height={20} src={'/logo.svg'} alt="Coplan Logo" />

          <Stack
            direction={'row'}
            spacing={4}
            display={['none', 'none', 'inherit']}
          >
            <Button variant={'outline'}>Sign up</Button>
            <Button variant={'ghost'}>Login</Button>
          </Stack>
        </Flex>
      </Container>
      <Box
        position={'relative'}
        overflow="hidden"
        minH={['100vh', '100vh', 'auto']}
        display="flex"
        flexDir={['column', 'column', 'column', 'row-reverse']}
      >
        <Container
          display={'flex'}
          flexDir="column"
          minH={['100vh', '100vh', 'auto']}
          maxW={['xl']}
        >
          <Flex flex={1} flexDir={'column'} pt={6} pb={10} h="100%">
            <Flex
              display={['flex', 'flex', 'none']}
              alignItems={'center'}
              justify={['center', 'center', 'space-between']}
              pt={8}
            >
              <Image
                width={120}
                height={20}
                src={'/logo.svg'}
                alt="Coplan Logo"
              />

              <Stack
                direction={'row'}
                spacing={4}
                display={['none', 'none', 'inherit']}
              >
                <Button variant={'outline'}>Sign up</Button>
                <Button variant={'ghost'}>Login</Button>
              </Stack>
            </Flex>
            <Flex
              flex={1}
              flexDirection="column"
              justifyContent={['center', 'center', 'flex-start']}
              rowGap={10}
            >
              <Box
                display={['block', 'block', 'none']}
                w="full"
                h={[72, '96']}
                position={'relative'}
              >
                <Image src={'/welcome.svg'} alt="Coplan welcome picture" fill />
              </Box>

              <Stack spacing={4} mt={[0, 0, 16]}>
                <Text
                  as={'h1'}
                  textAlign={['center', 'center', 'left']}
                  fontWeight="bold"
                  color={'dark.200'}
                  fontSize={['xl', '3xl', '4xl']}
                >
                  Manage Your Money, Together or Solo: The Ultimate Finance App
                </Text>
                <Text
                  color={'dark.100'}
                  fontSize={'xl'}
                  display={['none', 'none', 'block']}
                >
                  Take control of your finances with our app. Whether
                  you&apos;re managing your money solo, or with a partner or
                  friends, our user-friendly platform makes tracking your
                  finances easy. Set goals, track spending, and achieve
                  financial success today.
                </Text>
              </Stack>
            </Flex>

            <Stack
              display={['inherit', 'inherit', 'none']}
              bg={['transparent', 'transparent', 'red']}
              mt={'auto'}
              direction={['column', 'row']}
              spacing="4"
            >
              <Button w={'100%'} size={['lg']} bg={'brand.600'}>
                Login
              </Button>
              <Button w={'100%'} size={['lg']} bg="brand.400">
                Sign Up
              </Button>
            </Stack>
          </Flex>
        </Container>

        {/* Mobile decor */}
        <Box
          display={['block', 'block', 'none']}
          rounded={'full'}
          w={48}
          h={48}
          bgGradient="linear(to-r, brand.400, brand.50)"
          position={'absolute'}
          top={-14}
          left={-10}
          zIndex={-1}
        ></Box>
        <Box
          display={['block', 'block', 'none']}
          rounded={'full'}
          w={[32, 44]}
          h={[32, 44]}
          bgGradient="linear(to-r, brand.50, brand.400)"
          position={'absolute'}
          bottom={-14}
          right={-10}
          zIndex={-1}
        ></Box>
        {/* Tablet and desktop decor */}
        <Box display={['none', 'none', 'block']} bottom={0}>
          <Image
            width={700}
            height={500}
            src="/welcomepicture-desk.svg"
            alt="Welcome Coplan picture"
          />
        </Box>
      </Box>
    </>
  );
}
