import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import {
  Box,
  Button,
  Container,
  Divider,
  Flex,
  Spacer,
  Stack,
  Text,
} from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box position={'relative'} overflow="hidden" minH={'100vh'}>
        <Container display={'flex'} flexDir="column" minH={'100vh'}>
          <Flex flex={1} flexDir={'column'} pb={10} h="100%">
            <Box
              mt={4}
              w={[28, 36]}
              height={10}
              position={'relative'}
              mx="auto"
            >
              <Image src={'/logo.svg'} alt="Coplan Logo" fill />
            </Box>

            <Flex
              flex={1}
              flexDirection="column"
              justifyContent={'center'}
              rowGap={10}
            >
              <Box w="full" h={[72, '96']} position={'relative'}>
                <Image src={'/welcome.svg'} alt="Coplan welcome picture" fill />
              </Box>

              <Box>
                <Text
                  as={'h1'}
                  textAlign="center"
                  fontWeight="bold"
                  color={'dark.200'}
                  fontSize={['xl', '3xl']}
                >
                  Manage Your Money, Together or Solo: The Ultimate Finance App
                </Text>
                <Text display={['none']}>
                  Take control of your finances with our app. Whether you're
                  managing your money solo, or with a partner or friends, our
                  user-friendly platform makes tracking your finances easy. Set
                  goals, track spending, and achieve financial success today.
                </Text>
              </Box>
            </Flex>

            <Stack
              bg={['transparent', 'transparent', 'red']}
              mt={'auto'}
              direction={['column', 'row']}
              spacing="4"
            >
              <Button w={'100%'} size={['lg']} bg={'brand.600'}>
                Login
              </Button>
              <Button w={'100%'} size={['lg']} bg="brand.400">
                Sign Up
              </Button>
            </Stack>
          </Flex>
        </Container>

        {/* Mobile decor */}
        <Box
          rounded={'full'}
          w={48}
          h={48}
          bgGradient="linear(to-r, brand.400, brand.50)"
          position={'absolute'}
          top={-14}
          left={-10}
          zIndex={-1}
        ></Box>
        <Box
          rounded={'full'}
          w={[32, 44]}
          h={[32, 44]}
          bgGradient="linear(to-r, brand.50, brand.400)"
          position={'absolute'}
          bottom={-14}
          right={-10}
          zIndex={-1}
        ></Box>
      </Box>
    </>
  );
}
